services:
  opencode-chamber:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - "3000:3000"
    volumes:
      - "./opencode-config:/home/.config/opencode"
      - "./codes:/home/repositories"
    environment:
      - UI_PASSWORD=
      - OPENCHAMBER_HOST=0.0.0.0
    restart: unless-stopped
    network_mode: host
